development:
  password: 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
  theme_id: "80910614591"
  store: wondersauce-boilerplate.myshopify.com
production:
  password: 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
  theme_id: "40910614522"
  store: wondersauce-boilerplate.myshopify.com
