name: Deploy Shopify Production Theme

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  shopify:
    name: Shopify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: npm run deploy:production

      - name: Shopify
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_PRODUCTION_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
